export const HOUR = 60 * 60;
export const DEFAULT_TICKET_PRICE = 10n ** 16n;
export const DEFAULT_CREATOR_FEE = 10n ** 15n;
export const DEFAULT_DEVELOPER_FEE = 10n ** 15n;
export const DEFAULT_TOTAL_PRICE = DEFAULT_TICKET_PRICE + DEFAULT_CREATOR_FEE + DEFAULT_DEVELOPER_FEE;
